name: Run Go Script on Push to Main

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.16'

    - name: Check last commit message
      id: check_commit
      run: |
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
        if [[ "$LAST_COMMIT_MESSAGE" == *"Update file via GitHub Actions"* ]]; then
          echo "Last commit message indicates this workflow triggered the change. Exiting."
          echo "::set-output name=skip::true"
        else
          echo "Last commit message does not indicate this workflow triggered the change."
          echo "::set-output name=skip::false"
        fi

    - name: Check for Go script
      run: |
        if [ ! -f that.go ]; then
          echo "Go script not found. Failing the workflow."
          exit 1
        fi

    - name: Run Go script
      run: go run that.go

    - name: Retrieve commits.txt
      run: cat commits.txt


    - name: Configure Git
      if: steps.check_commit.outputs.skip == 'false'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push changes
      if: steps.check_commit.outputs.skip == 'false'
      run: |
        git add .
        git commit -m "Update file via GitHub Actions"
        git push origin main
