name: Run Go Script on Push to Main

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.16'

    - name: Check for Go script
      run: |
        if [ ! -f main.go ]; then
          echo "Go script not found. Failing the workflow."
          exit 1
        fi

    - name: Run Go script
      run: go run that.go

    - name: Retrieve commits.txt
      run: cat commits.txt
